### ISSUE TITLE
Segmentation fault when calling JSON.stringify on a jquery object

### ISSUE THREAD

**Issue by mag** [smparkes/env-js#6] opened 2010-03-12 17:55 UTC
This is on envjs version 0.2.0 and johnson 2.0.0.pre3
    $ envjsrb
    js> load('jquery-1.4.1.js')
    => nil
    js> var foo = jQuery("foo");
    => nil
    js> JSON.stringify(foo)
    Segmentation fault

**Comment by mag** [comment] 2010-03-12 17:57
I imagine the issue here is with johnson, not envjs, since JSON.stringify is implemented in native code in johnson. I posted here since it's only through envjs & jquery that I know how to reproduce this bug.

**Comment by smparkes** [comment] 2010-03-12 18:10
Reproduced. I'll check.

**Comment by smparkes** [comment] 2010-03-12 18:15
Interesting. SM is getting into an infinite recursion.

**Comment by smparkes** [comment] 2010-03-12 19:09
Yeah, SM doesn't do cycle detection: https://bugzilla.mozilla.org/show_bug.cgi?id=536161

Johnson currently isn't setting a stack limit and so it cores rather than throwing an exception. We'll fix that.

Gonna close this because it's a Johnson issue. FWIW, the Johnson test case is

x = {}
x.y = x
JSON.stringify(x)

**Closed as completed by smparkes** 2010-03-12 19:09 UTC
